apiVersion: apps/v1
kind: Deployment
metadata:
  name: bis-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bis-service
  template:
    metadata:
      labels:
        app: bis-service
    spec:
      containers:
      - name: bis-service
        image: vendettistudios/bis-service:latest
        ports:
        - containerPort: 3008
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 256Mi
