apiVersion: apps/v1
kind: Deployment
metadata:
  name: tms-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tms-service
  template:
    metadata:
      labels:
        app: tms-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3004"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: tms-service
          image: vendettistudios/tms-service:latest
          ports:
            - containerPort: 3004
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
