services:
  bis-service:
    build:
      context: ./BIS/nest-bis/bis-service
    ports:
      - '3000:3000'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  crm-service:
    build:
      context: ./CRM/nest-crm/crm-service
    ports:
      - '3001:3000'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3

  ims-service:
    build:
      context: ./WMS/IMS/nest-ims/ims-service
    ports:
      - '3002:3000'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002"]
      interval: 30s
      timeout: 10s
      retries: 3

  wo-service:
    build:
      context: ./WMS/WO/nest-wo/wo-service
    ports:
      - '3003:3000'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003"]
      interval: 30s
      timeout: 10s
      retries: 3

  erp-service:
    build:
      context: ./ERP/nest-erp/erp-service
    ports:
      - '3004:3000'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3004"]
      interval: 30s
      timeout: 10s
      retries: 3

  tms-service:
    build:
      context: ./TMS/nest-tms/tms-service
    ports:
      - '3005:3000'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3005"]
      interval: 30s
      timeout: 10s
      retries: 3

  oms-service:
    build:
      context: ./WMS/OMS/nest-oms/oms-service
    ports:
      - '3006:3000'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3006"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
