services:
  bis-service:
    build: ./BIS/nest-bis/bis-service
    ports:
      - "3001:3000"
    volumes:
      - ./BIS/nest-bis/bis-service:/usr/src/app
      - /usr/src/app/node_modules

  crm-service:
    build: ./CRM/nest-crm/crm-service
    ports:
      - "3002:3000"
    volumes:
      - ./CRM/nest-crm/crm-service:/usr/src/app
      - /usr/src/app/node_modules

  erp-service:
    build: ./ERP/nest-erp/erp-service
    ports:
      - "3003:3000"
    volumes:
      - ./ERP/nest-erp/erp-service:/usr/src/app
      - /usr/src/app/node_modules

  tms-service:
    build: ./TMS/nest-tms/tms-service
    ports:
      - "3004:3000"
    volumes:
      - ./TMS/nest-tms/tms-service:/usr/src/app
      - /usr/src/app/node_modules

  ims-service:
    build: ./WMS/IMS/nest-ims/ims-service
    ports:
      - "3005:3000"
    volumes:
      - ./WMS/IMS/nest-ims/ims-service:/usr/src/app
      - /usr/src/app/node_modules

  oms-service:
    build: ./WMS/OMS/nest-oms/oms-service
    ports:
      - "3006:3000"
    volumes:
      - ./WMS/OMS/nest-oms/oms-service:/usr/src/app
      - /usr/src/app/node_modules

  wo-service:
    build: ./WMS/WO/nest-wo/wo-service
    ports:
      - "3007:3000"
    volumes:
      - ./WMS/WO/nest-wo/wo-service:/usr/src/app
      - /usr/src/app/node_modules

  nginx:
    build: .
    ports:
      - "80:80"
    depends_on:
      - bis-service
      - crm-service
      - erp-service
      - tms-service
      - ims-service
      - oms-service
      - wo-service

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
