global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'microservices'
    static_configs:
      - targets: ['bis-service:3001', 'crm-service:3002', 'erp-service:3003', 'tms-service:3004', 'ims-service:3005', 'oms-service:3006', 'wo-service:3007']
