apiVersion: apps/v1
kind: Deployment
metadata:
  name: bis-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bis-service
  template:
    metadata:
      labels:
        app: bis-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3001"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: bis-service
          image: vendettistudios/bis-service:latest
          ports:
            - containerPort: 3001
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
