apiVersion: apps/v1
kind: Deployment
metadata:
  name: wo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wo-service
  template:
    metadata:
      labels:
        app: wo-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3007"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: wo-service
          image: vendettistudios/wo-service:latest
          ports:
            - containerPort: 3007
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
