apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        monitor: 'default'

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'microservices'
        static_configs:
          - targets:
            - 'bis-service.default.svc.cluster.local:3001'
            - 'crm-service.default.svc.cluster.local:3002'
            - 'erp-service.default.svc.cluster.local:3003'
            - 'tms-service.default.svc.cluster.local:3004'
            - 'ims-service.default.svc.cluster.local:3005'
            - 'oms-service.default.svc.cluster.local:3006'
            - 'wo-service.default.svc.cluster.local:3007'
